<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>try~catch</title>
</head>
<body>
    <h1>
        예상되는 에러를 try{code..} 영역에 배치하고, 만약 에러가 발생하면
        catch(err){code...} 영역에서 처리하는 예외처리 프로세스
    </h1>
    <ul>
        <li>
            try 영역 : 에러 발생 가능성이 있는 코드를 실행하는 곳
        </li>
        <li>
            catch(err) : 에러 발생시 예외처리를 하는 곳
        </li>
        <li>
            try~catch로 예외처리를 하면 프로세스가 멈추지 않고 지속시킬 수 있음.
        </li>
        <li>
            finally 영역 : 예외처리와 관계없이 무조건 코드를 실행하는 영역
        </li>
        <li>
            throw : 예외를 고의적으로 발생시키는 키워드 throw + 처리할 코드
        </li>
    </ul>

    <script>
        console.log('프로세스 시작~!!');

        function a(num){
            if(num > 10){
                throw new Error('10보다 큽니다.');
            }
        }

        try{
            console.log('경고창 실행 확인1');
            alerttt('경고창 실행');  //명령어 잘못 입력
            console.log('경고창 실행 확인2');
        }catch(err){
            console.log('catch영역');
            console.log(err.name);
            console.log(err.message);
             try{
                if(err.message != null){
                    throw new Error('222222222');
                }
                }catch(err2){
                    console.log(err2.name);
                    console.log(err2.message);
                }finally{
                    console.log('err2 finally 영역');
                }
        }finally{
            console.log('마지막 finally 영역...');
        }
        try{
               console.log("1111");
                a(11);
            }catch(err){
                console.log(err.name);
                console.log(err.message);
            }finally{
                console.log('err2 finally 영역');
            }
        console.log('프로세스 종료~!!');

    </script>
</body>
</html>